### ISSUE TITLE
Mediumish 

### ISSUE THREAD

**Issue by dkarthe** [wowthemesnet/mediumish-theme-jekyll#1]
Hi, I really impressed your creativity and thanks. In that theme I have got some errors. 
1.How do I hide newsletter subscriber form, it's in stable. 
2. In that bottom of archive posts, if I click that it shows 404.

**Comment by wowthemesnet** [comment]
Hi, @dkarthe , thanks for your kind words.
1. In _layout/default.html, remove the "bottom alert bar" section ([L101-113](https://github.com/wowthemesnet/mediumish-theme-jekyll/blob/master/_layouts/default.html#L101)).

2. Jekyll Arhives plugin doesn't work on GitHub Pages hosted sites (where the demo is). So if you host your website outside Github pages, you will not get any 404. If you do and still want to use the theme you could simply get rid of the categories.

Hope this helps,

Sal

**Comment by dkarthe** [comment]
Hi, @Sal, is there any  possible to "auto-hide alert bar" after few seconds.

**Comment by giswqs** [comment]
@wowthemesnet Thank you for developing such a great Jekyll theme. I am wondering when the Jekyll Archives plugin will work on GitHub Page. I can't wait to adopt this Jekyll theme when the archives plugin is supported. Thanks.
