### ISSUE TITLE
naming `.md` is type specific and every `.md` file from subfolders is not picked up

### ISSUE THREAD

**Issue by ankitdadhich** [wowthemesnet/mediumish-theme-jekyll#11]
Hi, 

First of all thanks for this awesome work. Am newbie to jekyll.

So right now when I put `my-new-info-page.md` it doesnt show up in output.
It works only when I follow this strict `yyyy-mm-dd-my-new-page.md` naming.

I might end up with 50+ `.md` file on my blog. So I would like to create subcategory folder in `_posts`
 like below, and generate similar output `_site` folder.

![image](https://user-images.githubusercontent.com/9630673/45014898-377ff000-b04a-11e8-97d5-d7a5c3675d29.png)

I tried playing with `_config.yaml` but no luck.
Is there any way that can be configured?

Thanks 
Ankit

**Comment by wowthemesnet** [comment]
Hi @ankitdadhich , have you tried to treat them as [drafts](https://jekyllrb.com/docs/posts/#drafts) and then `jekyll build --drafts` or `jekyll serve --drafts`. I know I've seen this solution somewhere but have never tested it myself.

**Comment by ankitdadhich** [comment]
Apology for late reply.
Here is the soultion

`collections:
  foldername :
    output: true
    permalink: /:collection/:title or permalink: /:collection/:path`

Keep either `permalink: /:collection/:title` or `permalink: /:collection/:path`.

By doing above one can get desired output.
