### ISSUE TITLE
The paginator URL is missing the host.

### ISSUE THREAD

**Issue by CatchZeng** [wowthemesnet/mediumish-theme-jekyll#111]
When I use [Nginx](https://www.nginx.com/) to load _site from jekyll build, the paginator URL does not load because of the missing host.

<img width="821" alt="屏幕快照 2019-10-03 上午9 46 25" src="https://user-images.githubusercontent.com/10027281/66093464-ed599d00-e5c2-11e9-8376-fb271998888e.png">

<img width="710" alt="屏幕快照 2019-10-03 上午9 46 48" src="https://user-images.githubusercontent.com/10027281/66093487-f8acc880-e5c2-11e9-8f7f-28a13899b048.png">

**Comment by miniesam** [comment]
It seems like your bug is the same as I've experienced.
And also, I think this [Pull Request](https://github.com/wowthemesnet/mediumish-theme-jekyll/pull/105) will be helpful to you.

**Comment by CatchZeng** [comment]
@miniesam You are great, thank you for your help.
