### ISSUE TITLE
404 File Not Found - when you click on tags

### ISSUE THREAD

**Issue by skalavala** [wowthemesnet/mediumish-theme-jekyll#12]
First of all, thank you for the woderful theme! Found a small bug - when you click on the tags in `jumbotron fortags` div, you get 404.

**Comment by abhishekmsharma** [comment]
Yes, and this is the only downside of this wonderful theme. I absolutely love this theme, but this is the sole reason I am planning to search for alternatives. :( 

Someone else asked the same question [here](https://github.com/wowthemesnet/mediumish-theme-jekyll/issues/1), and this what @wowthemesnet replied, 
> Unless jekyll-archives isn't listed soon, I am taking into consideration an alternative option. I'll wait for the moment to see how this proposal is received: jekyll/jekyll#6952

**Comment by skalavala** [comment]
Closing the issue as it appears Github currently doesn't support archives plug-in, and I have removed that section from my code anyway. I may look for an alternative at a later time, but I'm good for now. Thank you!
