### ISSUE TITLE
YAML header image URL

### ISSUE THREAD

**Issue by giswqs** [wowthemesnet/mediumish-theme-jekyll#15]
The example YAML header of markdown post uses images from the website directory, such as 
image: assets/images/2.jpg

Is it possible to use image from the internet? such as
image: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png

I tried, but it did not work. 

Any help will be appreciated.

**Comment by wowthemesnet** [comment]
Yes, you're right, it only works with the card thumbnail. I'll push an update within minutes.

**Comment by wowthemesnet** [comment]
Updated with the fix @giswqs .Thank you!
