### ISSUE TITLE
jumbotron image won't show up when webpage is viewed in one-column 

### ISSUE THREAD

**Issue by giswqs** [wowthemesnet/mediumish-theme-jekyll#16]
See screenshot below. Essentially, the jumbotron image won't display on a cellphone screen. Any solutions? Thanks. 
![](https://i.imgur.com/T1mpFK6.png)

**Comment by wowthemesnet** [comment]
Yes, thanks for reporting. Update coming today.

**Comment by wowthemesnet** [comment]
Fixed!
