### ISSUE TITLE
Bug: featured items thumbnails disappear on large viewport with Firefox

### ISSUE THREAD

**Issue by DirtyF** [wowthemesnet/mediumish-theme-jekyll#17]
Given I browse https://wowthemesnet.github.io/mediumish-theme-jekyll/ on Firefox 64.0, the featured items loose their background, thumbnail height equals zero when viewport is larger than 1200px

Screenshot

![mediumish-2018-12-20 22 18 34](https://user-images.githubusercontent.com/103008/50311607-15e62f80-04a6-11e9-983e-7d40626fb1aa.png)

**Comment by InfoSecRavindra** [comment]
Removing min-height from `wrapthumbnail` class works. It is a firefox bug.

More info.
https://stackoverflow.com/questions/14053206/css-min-height-not-working-on-mozilla-firefox

**Comment by InfoSecRavindra** [comment]
Solved it,
Changing `min-height` to `height` works without breaking anything.

Feel free to visit [Ravindra's Blog](https://infosecravindra.github.io) to make sure nothing broke.
