### ISSUE TITLE
Google Analytics Support

### ISSUE THREAD

**Issue by trmittal24** [wowthemesnet/mediumish-theme-jekyll#175]
Hey Mate, 
Thanks for providing with the wonderful template!
I was facing some troubles with Google Analytics, can you please help?

I created a new Analytics account and a data stream for my site, I got the streamcode and pasted it in _config.yml.

However, the Analytics page on google is always reflecting 0 views. 

Is there is something else I need to do?

Thanks
Tarun

**Comment by trmittal24** [comment]
This is fixed. I replaced 

`<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create', '{{site.google_analytics}}', 'auto');
ga('send', 'pageview');
</script>`

with 

`
<script async src="https://www.googletagmanager.com/gtag/js?id={{site.google_analytics}}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '{{site.google_analytics}}');
</script>
` 


This was required for Stream ID starting with **G-** instead of **UA-**

**Comment by techtreehouse** [comment]
Thank you for this! If anyone is looking for where to replace it, the code is in "_layouts/default.html"
