### ISSUE TITLE
added tags and categories to mediumish theme

### ISSUE THREAD

**Issue by Bharathbrothers** [wowthemesnet/mediumish-theme-jekyll#19]
https://github.com/Bharathbrothers/mediumish-theme-with-tags-and-categories

added tags and categories to this theme taken from codinfox. once go through it and if useful , can add this feature to this theme.

**Comment by Bharathbrothers** [comment]
Hey!  @InfosecRavindra I have added tags and categories to my blog!   at the Explore section in mediumish theme.  
starksources.github.io/myblog

**Comment by InfoSecRavindra** [comment]
Great, I have seen it but I am using collections so categories would make things redundant.

**Comment by GiacomoLaw** [comment]
@Bharathbrothers this is perfect! How can I add this to my site?

Thanks

**Comment by wowthemesnet** [comment]
I'll push an update soon here soon, so you'll not have to manually add it. This is something I've always had in mind doing anyway :)

**Comment by GiacomoLaw** [comment]
Awesome! Are you planning to add search?

Love the theme :)

**Comment by wowthemesnet** [comment]
Yes, I am working on this at the very moment :)

**Comment by GiacomoLaw** [comment]
Can't wait, thank you!

**Comment by Bharathbrothers** [comment]
Hey!! I have added all these features to my **blog**.! you can check it out.
https://starksources.github.io/myblog/

**Comment by wowthemesnet** [comment]
@Bharathbrothers looks great, I saw it! Also, Mediumish is now updated with category links compatible with Github pages. Added search and SEO tags, too.

**Comment by GiacomoLaw** [comment]
Yay! How can I update my repo?

Thanks for the support :)

**Comment by Bharathbrothers** [comment]
You can update your repo to the latest update by creating a new pull request and compare it with your repo and you will be able to merge it to your repo.
You will get all the latest updates.

**Comment by Bharathbrothers** [comment]
> @Bharathbrothers looks great, I saw it! Also, Mediumish is now updated with category links compatible with Github pages. Added search and SEO tags, too.

Yes.! I have seen it. It is Awesome. Thank you for giving us a great template for blogging.

**Comment by GiacomoLaw** [comment]
My repo isn't a fork, I guess I can still do this?

**Comment by Bharathbrothers** [comment]
yes, you can do it manually. I don't think that there is a way to update it automatically without forking.
if you find any, let me know.
