### ISSUE TITLE
122 requests made on blog post load

### ISSUE THREAD

**Issue by welkie** [wowthemesnet/mediumish-theme-jekyll#20]
I was wondering if this is an issue the maintainers are aware of. There seems to be a lot of requests made upon a post being loaded, and some of them look sketchy too. The domains include "doubleclick" etc. I got 122 requests during this particular load but I also saw 165 requests when I ran it a minute ago:

![blog_requests](https://user-images.githubusercontent.com/7719209/50871730-981d9180-138a-11e9-8434-5d918f0fb6e9.png)

**Comment by wowthemesnet** [comment]
Yes, this is caused by Disqus not by the theme. So you can simply remove Disqus.
