### ISSUE TITLE
archive page not working in GitHub hosted pages

### ISSUE THREAD

**Issue by mahdiit** [wowthemesnet/mediumish-theme-jekyll#23]
i test every thing work but archive do not, any solution?

i read GitHub pages guide and it does not support Jekyll archive plugin
https://help.github.com/articles/configuring-jekyll-plugins/

so i think that i must use liquid method described here
https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_config.yml 

more about it:
https://mmistakes.github.io/minimal-mistakes/docs/configuration/#archive-settings

**Comment by wowthemesnet** [comment]
Yes, unfortunately GitHub Pages hosted sites do not support `jekyll-archives`. A different & simple approach could be [this](https://github.com/wowthemesnet/mundana-theme-jekyll/blob/master/_pages/categories.html), I adopted it in [my latest Jekyll theme](https://wowthemesnet.github.io/mundana-theme-jekyll/) for 100% Github pages compatibility:
