### ISSUE TITLE
CSS not loading

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#24]
![image](https://user-images.githubusercontent.com/9038673/52521616-8bce7200-2c71-11e9-9ae7-4dee3deae282.png)

My site looks like this. How can I fix it?

Thanks

**Comment by wowthemesnet** [comment]
Did you set the correct base path in [_config.yml](https://github.com/wowthemesnet/mediumish-theme-jekyll/blob/master/_config.yml#L7)?

**Comment by GiacomoLaw** [comment]
Just updated, and seemed to have been fixed. Thanks! :)

The site is https://takanodan.net

**Comment by GiacomoLaw** [comment]
Is there any way to force cache clear after repo update?
