### ISSUE TITLE
Author box not loading

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#25]
Site: https://takanodan.net

Author box is not loading, the image and the author info do not load.

**Comment by wowthemesnet** [comment]
Did you update your _config.yml [authors](https://github.com/wowthemesnet/mediumish-theme-jekyll/blob/master/_config.yml#L12)?

**Comment by GiacomoLaw** [comment]
Found the issue, I hadn't changed this: https://github.com/wowthemesnet/mediumish-theme-jekyll/blob/33de3f7673264f0568d395b16c6931450830c504/_config.yml#L14

My bad, thanks for the help.
