### ISSUE TITLE
Tags cut off on mobile

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#26]
The tags are cut off on mobile. 

![Issue](https://i.imgur.com/h9hia1u.jpg)

Site: https://takanodan.net

Thanks

**Comment by wowthemesnet** [comment]
Yes, I see, thanks for reporting, I'm taking care of this now.

**Comment by GiacomoLaw** [comment]
Thanks. How can I keep updated without overwriting my site?

Thanks for the quick fixes 😄

**Comment by Bharathbrothers** [comment]
Hey, you can check out this.! https://github.com/StarkSources/myblog
![blog](https://user-images.githubusercontent.com/24895239/52527533-fde59c00-2cef-11e9-9067-4b3b2c49529f.JPG)

https://starksources.github.io/myblog/

**Comment by wowthemesnet** [comment]
I'll push an update tomorrow for the CSS fix, it's 01:43AM here, battery low lol. 

For  updates, check out sync fork tutorial: https://help.github.com/articles/syncing-a-fork/

**Comment by GiacomoLaw** [comment]
Awesome, thanks!
