### ISSUE TITLE
Requesting a new feature of Login/Signup using Firebase to this theme

### ISSUE THREAD

**Issue by Bharathbrothers** [wowthemesnet/mediumish-theme-jekyll#27]
This will help us to add more features to the theme and can also add personalized **recommendations**  to the users. 

_Sent from my HM 2LTE-IN using [eHub](https://github.com/thermatk/FastHub-Libre/)_

**Comment by GiacomoLaw** [comment]
Not really sure this is needed. When you get to login I don't think that many people would use Jekyll.
