### ISSUE TITLE
Review option

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#29]
Any way you could add the ability to have something like this?

![image](https://user-images.githubusercontent.com/9038673/52536204-644dd700-2d4f-11e9-92d0-e613ae0e08a7.png)

Or the ability to add the code into each post? In addition, is there any way to get SEO like this:

![image](https://user-images.githubusercontent.com/9038673/52536206-73cd2000-2d4f-11e9-8d2e-8b2b84eb9537.png)

Thanks!

**Comment by GiacomoLaw** [comment]
From this site: http://www.adventuresinpoortaste.com/2017/08/22/that-time-i-got-reincarnated-as-a-slime-vol-1-review/

Would love to have the ability to do this.

**Comment by wowthemesnet** [comment]
I think I will.

**Comment by GiacomoLaw** [comment]
For the time I'm using custom CSS and it works well:

**Comment by GiacomoLaw** [comment]
For the time being I'm using custom CSS and it works well. Using Font Awesome with the stars to give a stars rating.

https://takanodan.net/slime-review/

**Comment by wowthemesnet** [comment]
Yes, but needs integration https://developers.google.com/search/docs/data-types/review-snippet

**Comment by GiacomoLaw** [comment]
Ah, I don't mean for the users to give star ratings. I only mean for the reviewer to allow the user to easily see the a quick overview of what the reviewer thinks :)

Thanks for the continued support btw, love the theme.

**Comment by wowthemesnet** [comment]
Yes, I understood.

**Comment by wowthemesnet** [comment]
Done. Example here: https://wowthemesnet.github.io/mediumish-theme-jekyll/customer-service/

**Comment by GiacomoLaw** [comment]
Thanks so much! Can we use ratings such as 3.5?

**Comment by wowthemesnet** [comment]
Unfortunately I only worked on the basics. I'll do it though sometime soon.

**Comment by GiacomoLaw** [comment]
Awesome, thanks!

**Comment by GiacomoLaw** [comment]
I can take a look at allowing `.` stars to be added.

**Comment by wowthemesnet** [comment]
It's okay, I'm taking care of this right now, thanks!

**Comment by GiacomoLaw** [comment]
Awesome, thank you!

**Comment by wowthemesnet** [comment]
Ok, half stars supported.

**Comment by GiacomoLaw** [comment]
Thanks!

**Comment by wowthemesnet** [comment]
After one month :)

![rating-example](https://user-images.githubusercontent.com/5597992/54702413-789ba580-4b3f-11e9-88ac-d6b1e99c65de.png)

Is it okay if I use this screenshot to showcase the rating implementation in Mediumish?

**Comment by GiacomoLaw** [comment]
Sure thing, feel free to!
