### ISSUE TITLE
Post not showing

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#30]
```
---
layout: post
title:  "That Time I Got Reincarnated as a Slime Ep. 1 - 16 review"
author: giacomo
categories: [ Anime ]
image: assets/images/posts/2-slime/slime.jpg
featured: false
hidden: false
---
```

That is my top matter, and my title is `2019-02-10-slime-review.md`. Why is this post not showing up?

Thanks

**Comment by wowthemesnet** [comment]
Remove hidden:false.

**Comment by GiacomoLaw** [comment]
Will do, thanks

**Comment by GiacomoLaw** [comment]
Nope, still not showing

**Comment by wowthemesnet** [comment]
I'm sorry, I'm on my phone now and can't do much. Do you have your code on Github?

**Comment by GiacomoLaw** [comment]
Yep, made public temporarily: https://github.com/GiacomoLaw/takanodan/

**Comment by wowthemesnet** [comment]
Can you also remove featured and test?

**Comment by GiacomoLaw** [comment]
Sure, give me a second

**Comment by GiacomoLaw** [comment]
Showing up now! How do I include an image inline out of interest? My way doesn't seem to be working :/

Thanks!

**Comment by wowthemesnet** [comment]
So either featured:true and hidden:true if you want to make them appear on top, either none to show them in All stories.

Image 
![Alt text](/path/to/img.jpg)

**Comment by GiacomoLaw** [comment]
Okay, thanks. I think I did that with the image. Here is the image: https://github.com/GiacomoLaw/takanodan/blob/master/assets/images/posts/2-slime/stabbing.JPG

Here is how I linked it: ![The stabbing](/assets/images/posts/2-slime/stabbing.jpg)

Thanks!

**Comment by wowthemesnet** [comment]
Look here https://github.com/wowthemesnet/mediumish-theme-jekyll/blob/master/_posts/2018-06-12-powerful-things-markdown-editor.md

Right before "references list"

**Comment by GiacomoLaw** [comment]
Awesome, thanks!
