### ISSUE TITLE
Title does not show on feed

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#31]
Hello,

Thanks for adding a feed feature. However, the title does not show when adding it with Inoreader.

![](https://i.imgur.com/3zfeMdK.jpg)

Thanks!

**Comment by wowthemesnet** [comment]
Thanks for this, fixed it. Make sure you edit your [site title](https://github.com/wowthemesnet/mediumish-theme-jekyll/blob/master/_config.yml#L3).
