### ISSUE TITLE
Having posts with duplicate names causes an error

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#32]
Say I have something called `2019-02-11-shield-hero`, and something called `2019-02-10-shield-hero`. The slug is always `shield-hero`, and therefore only loads in the latest version. Could this be fixed somehow, like having a `-2` at the end of the slug automatically?

Thanks

**Comment by wowthemesnet** [comment]
Unless you're not adding the dates in  [permalink](https://github.com/wowthemesnet/mediumish-theme-jekyll/blob/master/_config.yml#L12) to differentiate them, you'll have to manually change the name. 

Permalink with dates: `permalink: /:year/:month/:day/:title/`

**Comment by GiacomoLaw** [comment]
So I just add `permalink: /:year/:month/:day/:title/`

And it is in form such as `2019/02/14/shield`

Thanks!

**Comment by GiacomoLaw** [comment]
If I use this will it still work?

`permalink: /:year/:month/:title/`

Thanks

**Comment by wowthemesnet** [comment]
Sure, whatever you want, you decide the structure, it should work.

**Comment by GiacomoLaw** [comment]
Thanks!
