### ISSUE TITLE
Favicon on mobile showing as the old m favicon

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#36]
https://takanodan.net/favicon.ico

The favicon on mobile is still showing the default theme icon, despite me having updated it. How can I fix this?

Thanks

**Comment by wowthemesnet** [comment]
Clear phone's browser cache.

**Comment by GiacomoLaw** [comment]
Thanks, odd that private browsing which is cacheless didn't fix it like it normally does. Thanks.
