### ISSUE TITLE
I can't add site on Google Search Console

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [wowthemesnet/mediumish-theme-jekyll#37]
I have tried to add the website on google search console but it does not verify my property.
Is this theme blocking google bots at the custom domain?

**Comment by wowthemesnet** [comment]
No. What is your website URL?

**Comment by GiacomoLaw** [comment]
I have managed to add both my sites using this theme. I would suggest adding the additional page, as it is the most robust option imo.

**Comment by GiacomoLaw** [comment]
You may have to wait a little bit for the changes to come into affect.

**Comment by rahulkumarsingh73690** [comment]
Here is the website url - https://www.andrimo.com/

**Comment by rahulkumarsingh73690** [comment]
I tried to add via domain verification. Now the website is verified but Robots.txt error found. I checked my website via Chrome Audit but everything is fine. so why this is happening?

![search console - robots txt tester - https___www andrimo com_ - google chrome 16-02-2019 11_21_04](https://user-images.githubusercontent.com/37482171/52895225-4237d700-31dd-11e9-9f6f-444958cddcc7.png)

**Comment by wowthemesnet** [comment]
This isn't theme related, but I noticed your sitemap is linked to http while robots are called from https. Now I'm not sure this would solve it but, please, try to add the https map in your robots.txt file like so:

Sitemap: https://andrimo.com/sitemap.xml

**Comment by rahulkumarsingh73690** [comment]
I removed ssl now fixed. But can you please tell me where from i can change http:// to https: i generated sitemap from Jeykll Sitemap Plugin

**Comment by GiacomoLaw** [comment]
Add this to .htaccess

```
RewriteEngine On 
RewriteCond %{SERVER_PORT} 80 
RewriteRule ^(.*)$ https://www.example.me/$1 [R,L]
```

This forces https

**Comment by rahulkumarsingh73690** [comment]
There is no way to add htaceess file in jeykal theme

**Comment by GiacomoLaw** [comment]
Works for me.

**Comment by rahulkumarsingh73690** [comment]
In my Github Domain Setting it says Unavailable for your site because your domain is not properly configured to support HT
![https](https://user-images.githubusercontent.com/37482171/52896314-03f5e400-31ec-11e9-9ce6-0342ba34b37a.JPG)
TPS

**Comment by GiacomoLaw** [comment]
You deleted your CNAME in your repository.

**Comment by rahulkumarsingh73690** [comment]
NO, i have cname in my directory

**Comment by GiacomoLaw** [comment]
Can you link the repo you’re talking about?

**Comment by rahulkumarsingh73690** [comment]
In CNAME file only one line - 
www.andrimo.com

Is it Right?

**Comment by rahulkumarsingh73690** [comment]
Here is the link - https://github.com/andrimoopensource/website/

**Comment by GiacomoLaw** [comment]
Try removing the www. From the cname. Then wait some time for https to come up, it can take some time.

**Comment by rahulkumarsingh73690** [comment]
Okay i will try

**Comment by rahulkumarsingh73690** [comment]
Still Not Working

**Comment by rahulkumarsingh73690** [comment]
I Used this IP to connect Domain - 185.199.109.153 

Is it Right?

**Comment by wowthemesnet** [comment]
Is the robots.txt fixed?

**Comment by rahulkumarsingh73690** [comment]
Yes if i turn off ssl from cloudflare but i want ssl

**Comment by wowthemesnet** [comment]
So it's an issue of requesting https from http.
So leave your SSL just change your robots.txt to point to https://andrimo.com/sitemap.xml
Simply edit your robots file and add an s

**Comment by rahulkumarsingh73690** [comment]
Added S in Robots.txt but still not fixed. See the robots txt file https://www.andrimo.com/robots.txt

**Comment by rahulkumarsingh73690** [comment]
I think this error is coming from setting because I can't enable SSL from GitHub
![https](https://user-images.githubusercontent.com/37482171/52896626-a748f800-31f0-11e9-9779-6c3de797d0d3.JPG)

**Comment by wowthemesnet** [comment]
Then let's debug why you cant enforce https

**Comment by rahulkumarsingh73690** [comment]
How?

**Comment by rahulkumarsingh73690** [comment]
I connected domain through Cloudflare

**Comment by wowthemesnet** [comment]
Contact Gihub support staff.

**Comment by wowthemesnet** [comment]
https://github.community/t5/GitHub-Pages/How-to-enable-https-support-on-custom-domains/td-p/6894

**Comment by wowthemesnet** [comment]
This is where you can contact them directly and let them know about the  "enforce hpps problem" 
https://github.com/contact

**Comment by rahulkumarsingh73690** [comment]
Thanks
