### ISSUE TITLE
Add support for Jekyll admin

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#39]
Adding support for this: https://github.com/jekyll/jekyll-admin

Would be great. Planning on using Mediumish for a few clients, and they would love the ability to use this as it's a lot easier.

Thanks! 😄

**Comment by wowthemesnet** [comment]
But I can't see how this would make their life easier. They'd still have to know how to install their Jekyll website, the jekyll admin plugin is just a local way of dealing with posta. And if they know how to install Jekyll I am sure they have no problem generating a post :)

**Comment by GiacomoLaw** [comment]
My bad, thought it could be done serverside.

**Comment by wowthemesnet** [comment]
Unfortunately no :(
