### ISSUE TITLE
when click other navbar elements, it doesnt be active

### ISSUE THREAD

**Issue by erkanceylan** [wowthemesnet/mediumish-theme-jekyll#4]
on the navbar, when i click and open other pages like about or download active element always home. how can i change

**Comment by Mutmatt** [comment]
Little late but it looks static at the moment.

`<li class="nav-item active">                
                <a class="nav-link" href="index.html">Blog</a>
                </li>`

It shouldn't be a huge amount of work to make it active if you are in that URI zone.
