### ISSUE TITLE
Add spoiler class to hide text in a blur, and reveal on click?

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#41]
Something like Discourse has that can be revealed on a click.

![image](https://user-images.githubusercontent.com/9038673/52916586-6a0c6500-32d9-11e9-85e0-725223e0bbb3.png)

![image](https://user-images.githubusercontent.com/9038673/52916588-6d9fec00-32d9-11e9-9231-b9b31a085bb9.png)

https://github.com/discourse/discourse/blob/2a007bafa218afde0b3f6032917571a574d3d1ce/spec/components/pretty_text_spec.rb#L474

This would be a great addition!

Thanks

**Comment by vireakpanha** [comment]
Can I work on this?

**Comment by GiacomoLaw** [comment]
@vireakpanha you don’t ha e to request to work on an issue 😉

**Comment by wowthemesnet** [comment]
@vireakpanha please, do! @GiacomoLaw is right 👍

**Comment by GiacomoLaw** [comment]
@vireakpanha do you have any update on this? Thanks

**Comment by wowthemesnet** [comment]
You mean like hiding spoilers inside an article or hiding all article?

**Comment by wowthemesnet** [comment]
Done. Example here: https://wowthemesnet.github.io/mediumish-theme-jekyll/quick-start-guide/

**Comment by GiacomoLaw** [comment]
Thanks so much!

**Comment by GiacomoLaw** [comment]
Is there a way to blur them, and in click show? So the page dynamic doesn’t change?

Thanks!

**Comment by wowthemesnet** [comment]
Something like that?

![blurred-spoiler](https://user-images.githubusercontent.com/5597992/53644080-5f898e00-3c3e-11e9-868f-e4a81a235d10.png)

**Comment by GiacomoLaw** [comment]
Yep! 🙂

**Comment by wowthemesnet** [comment]
But the reveal button should still be there, right?

**Comment by GiacomoLaw** [comment]
No, just clicking on it should show it.

**Comment by wowthemesnet** [comment]
What if the people don't know they can reveal it with a click

**Comment by GiacomoLaw** [comment]
Maybe have a small box when you mouseover like on trakt.tv

**Comment by wowthemesnet** [comment]
Yes, that's better. It's on my to do list.

**Comment by GiacomoLaw** [comment]
Or just change the cursor to the click one, would be great. Can you link the branch for this? I would happily take a look.

Thanks

**Comment by wowthemesnet** [comment]
https://wowthemesnet.github.io/mediumish-theme-jekyll/quick-start-guide/ How about that? If you can't see the blurred text yet, please, empty cache.

**Comment by GiacomoLaw** [comment]
That's great! Thanks so much 😄

**Comment by GiacomoLaw** [comment]
Spoiler class isn't working for me for some reason on the site, was working locally:

https://github.com/GiacomoLaw/takanodan/blob/master/_posts/2019-02-11-shield-hero.md

On this post:

https://takanodan.net/2019/02/shield-hero/

Thanks!

**Comment by wowthemesnet** [comment]
the screen.css doesn't look updated yet: https://takanodan.net/assets/css/screen.css

**Comment by GiacomoLaw** [comment]
Odd, let me take a look. Thanks!

**Comment by GiacomoLaw** [comment]
That fixed it, sorry for my stupidity and thanks!
