### ISSUE TITLE
Mailjet integration?

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#42]
Hi there,

How would I use the Mailchimp box for Mailjet?

Thanks!

**Comment by wowthemesnet** [comment]
I did a test, here's how I got it quick.

1. Create a widget, enter expert mode and strip the title and description. Then save widget, copy the generated frame.

2. In Mediumish, replace the entire [alertbar div](https://github.com/wowthemesnet/mediumish-theme-jekyll/blob/master/_layouts/default.html#L133) with:

```
<div class="alertbar p-0 bg-transparent shadow-none">
    <iframe frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://app.mailjet.com/widget/iframe/3O0A/bl8" width="100%" height="90" class="d-flex"></iframe>        
</div>
```
Only replace the `src` frame with yours.

Of course you can adjust its look more in Mailjet's expert mode, but this was just a basic quick example. Hope this helps you and anyone else!

**Comment by GiacomoLaw** [comment]
Will do, thank you very much"
