### ISSUE TITLE
Add ability to easily add adsense

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#51]
Below the title and above the content. This would be great!

**Comment by wowthemesnet** [comment]
I need help to integrate Adsense. I don't have an Adsense account and it is difficult for me to test.

**Comment by GiacomoLaw** [comment]
https://support.google.com/adsense/answer/181950?hl=en-GB

That should help you out 🙂

**Comment by wowthemesnet** [comment]
Ok, but  I need to visually see the ads for aesthetic reasons on implementation.

**Comment by GiacomoLaw** [comment]
Ah, I am not sure about that. I think you would have to get your own ID, sorry.

**Comment by wowthemesnet** [comment]
Yes,  I thought so too unfortunately. Maybe someone will work on this if interested.

**Comment by GiacomoLaw** [comment]
I will take a look on my site once I get my larger site authorized with it :)

**Comment by GiacomoLaw** [comment]
Got my application approved so will look at adding this over the weekend. 

Thanks

**Comment by wowthemesnet** [comment]
That's great news! Looking forward to. Here's a good article if you need inspiration: https://mycyberuniverse.com/add-google-adsense-matched-content-jekyll-website.html

**Comment by GiacomoLaw** [comment]
Thanks! Will create a request if I get it figured out.

**Comment by rahulkumarsingh73690** [comment]
You will implement Adsense ads in the post (After Starting article and End of the Article) by doing a simple method.

**Comment by wowthemesnet** [comment]
Thanks @rahulkumarsingh73690 , I am waiting for @GiacomoLaw for a live demo on website to see how it looks in matter of design (paddings, margins etc).

**Comment by GiacomoLaw** [comment]
Thanks, I am waiting for my site to be approved.

**Comment by wowthemesnet** [comment]
Ok, so I made an Adsense account for this. Where do you think it's best to place the ad?  Under title?

**Comment by GiacomoLaw** [comment]
Yes, under the header before content would be good.

**Comment by wowthemesnet** [comment]
Ok, done. I only added one under header. If others will find useful, I'll add more places with time.

Change to "enabled" in [yml](https://github.com/wowthemesnet/mediumish-theme-jekyll/blob/master/_config.yml#L64) and change pub id + slot to track.

**Comment by GiacomoLaw** [comment]
Awesome, thank you!
