### ISSUE TITLE
Use filter: blur to blur spoilers

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#53]
This is a better method, however I have tried it but it blurs the tooltip and I am unsure how to fix that.

`filter: blur(8px);`

Thanks! 😄

**Comment by wowthemesnet** [comment]
I don't see anything wrong with text shadow. If you want to make it stand out a little more you can darken it a bit:

`text-shadow: 0 0 6px rgba(0,0,0,0.4);`

Blur filter isn't that flexible for our case.

**Comment by GiacomoLaw** [comment]
Ah, the issue is that text shadow is readable, so the user can see the spoiler.

**Comment by wowthemesnet** [comment]
Where is it readable?

**Comment by GiacomoLaw** [comment]
See: https://takanodan.net/2019/03/death-note/

The text can be read even when blurred. 

Thanks!

**Comment by wowthemesnet** [comment]
What eagle eye do you have, I can't understand a word, lol. Are you seeing what I'm seeing?

![2019-03-01_23h24_43](https://user-images.githubusercontent.com/5597992/53667283-3c300480-3c79-11e9-9fbf-afd4b30c975c.png)

**Comment by wowthemesnet** [comment]
You can use this `text-shadow: 0 0 10px rgba(0,0,0,0.2);` to blur it even more. Or replace 10px with whatever you need.

**Comment by GiacomoLaw** [comment]
Yep, I can easily read that lol. Sure, I’ll give that a go. Thanks, I appreciate it.

**Comment by wowthemesnet** [comment]
Were you able to acomplish it? Can you still see the text?

**Comment by GiacomoLaw** [comment]
Yep, I updated with your suggestion and now it cannot be seen :)

Thanks!
