### ISSUE TITLE
Clicking on single categories on mobile doesn’t work 

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#54]
https://takanodan.net/categories#anime

Clicking on the single category does not work.

**Comment by wowthemesnet** [comment]
Since fixing the 2 word category, they now respect the capitalization if present

https://takanodan.net/categories#Anime

**Comment by GiacomoLaw** [comment]
Ah, makes sense. Thanks
