### ISSUE TITLE
Sort categories in jumbotron by most used

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#55]
This would lead to a better user experience, as they would be able to see the most written about content.

Thanks 😄

**Comment by wowthemesnet** [comment]
Where? In the categories page?

**Comment by wowthemesnet** [comment]
There's a module, I'm not sure this will work on Github hosted pages. But if you feel adventurous: https://gist.github.com/somic/852008#file-sorted_categories_plugin-rb

**Comment by wowthemesnet** [comment]
If anyone has a solution without a plugin, I'd happily merge.

**Comment by GiacomoLaw** [comment]
Thanks for the help 🙂
