### ISSUE TITLE
Implement Lazy Load Images

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [wowthemesnet/mediumish-theme-jekyll#63]
Is there any way to implement lazy load images in this theme. Please answer @wowthemesnet @GiacomoLaw

**Comment by GiacomoLaw** [comment]
https://github.com/kenchan0130/jekyll-lazy-load-image

Not sure if it works on GitHub pages however.

**Comment by rahulkumarsingh73690** [comment]
I tried this one by Jeykll - https://jekyllcodex.org/without-plugin/lazy-loading/ but the problem is it loads immediately after started loading the page. I am trying to do as on scroll effect.

**Comment by GiacomoLaw** [comment]
That’s what lazy load does, as it refers image loading till the main content is there.

**Comment by rahulkumarsingh73690** [comment]
I got the Best solution for lazy loading images but I do not understand how to implement on this theme. Here is the [Demo](http://lazyload.demo.mxbry.com/) and Here is the [Repository](https://github.com/max-barry/demo.lazyload) of the Demo Page.

**Comment by rahulkumarsingh73690** [comment]
Woul

**Comment by rahulkumarsingh73690** [comment]
Please check this one.

**Comment by GiacomoLaw** [comment]
Works well for me on my site. Thanks for adding!

**Comment by rahulkumarsingh73690** [comment]
Thanks Sai for implementing lazy load. I am waiting for this features from 😴😴😴
