### ISSUE TITLE
Issue in Meta Data

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [wowthemesnet/mediumish-theme-jekyll#64]
Repeating title tags issue. See image below

![What is Android System WebView – All About System WebView _ Andrimo - Google Chrome 13-03-2019 11_12_30](https://user-images.githubusercontent.com/37482171/54256179-21b33080-4581-11e9-92ef-a1e5f361b17f.png)

**Comment by leninalbertolp** [comment]
That's because of the jekyll seo tag plugin, add title=false to the liquid tag of that plugin.

More info: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md#disabling-title-output

**Comment by rahulkumarsingh73690** [comment]
Thanks, Title tag issue fixed.
