### ISSUE TITLE
Sharing padding on sites with headers?

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#67]
I added a header to my site https://takanodan.net. How can I reduce the amount of padding until you scroll down so sharing is not hidden on smaller screens?

Thanks!

**Comment by wowthemesnet** [comment]
Yes, I know what you have there. I will change something right in the theme because maybe others too get the same issue on large headers.

**Comment by GiacomoLaw** [comment]
Thanks, appreciate it

**Comment by wowthemesnet** [comment]
Done. I'm waiting to see it live with your header though. Probably needs empty cache since css is changed.

**Comment by GiacomoLaw** [comment]
Great, I’ll update when I get home. I’ll close this comment and if I don’t update it’s all good.
