### ISSUE TITLE
Fix Author image padding

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [wowthemesnet/mediumish-theme-jekyll#68]
Author image is not showing in right place in Mobile. Please see image below. I prefer you to show image in middle not side.
![Screenshot_2019-03-20-22-12-07](https://user-images.githubusercontent.com/37482171/54702799-94ae3f80-4b5d-11e9-890b-b5054de5756e.png)

**Comment by wowthemesnet** [comment]
Let me check!

**Comment by GiacomoLaw** [comment]
Getting the same on iOS.

**Comment by wowthemesnet** [comment]
Yes, I see it. Pushing a fix right now.

**Comment by rahulkumarsingh73690** [comment]
Please implement lazy load image I opened issue already 10 days ago.

**Comment by GiacomoLaw** [comment]
If you desperately need the feature, you can implement it yourself. At a glance doesn’t look to taxing. 

Please don’t push authors to add features. This is a free and open source theme, so it’s easy enough to add yourself. 🙂

**Comment by wowthemesnet** [comment]
:)

**Comment by rahulkumarsingh73690** [comment]
No it's not my personal bcoz it increases page speed and helps rank better.

If admin tell me that he can't implement then I will try.

**Comment by GiacomoLaw** [comment]
Page speed only impacts ranking if your site is *incredibly* slow. See the Google Webmasters blog post on this: https://webmasters.googleblog.com/2018/01/using-page-speed-in-mobile-search.html?m=1

Also maybe serve your images in `webp` format, as this can greatly decrease loading time.

**Comment by rahulkumarsingh73690** [comment]
Thanks for fixing.

**Comment by wowthemesnet** [comment]
Ok, fixed.

@rahulkumarsingh73690 , it's not that I can't implement it, it's a project I am very fond of and I maintain it the best way I can. The problem is time. I left the issue opened and labeled it so I can take care of it whenever I can. Hope you understand. Also, anyone is more than welcome to contribute!

**Comment by rahulkumarsingh73690** [comment]
Okay Thanks. You are the best I am using your theme in WordPress website also. Love you

**Comment by wowthemesnet** [comment]
Thanks for the nice words!
