### ISSUE TITLE
Add Table of Content

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [wowthemesnet/mediumish-theme-jekyll#69]
Add Table of content support on blog posts. https://blog.webjeda.com/jekyll-toc/

**Comment by wowthemesnet** [comment]
[Demo](https://wowthemesnet.github.io/mediumish-theme-jekyll/education/)
Use `toc: true` in post where you want toc.

**Comment by rahulkumarsingh73690** [comment]
Thanks it's on right place before first header.

**Comment by rahulkumarsingh73690** [comment]
Thanks for adding but if it is after a 1st paragraph or before the first header then that is best for us.

**Comment by wowthemesnet** [comment]
I'll see what I can do.

**Comment by wowthemesnet** [comment]
Would it make sense to set an yaml paragraph before TOC like this?

```
---
layout: post
title:  "Education must also train one for quick, resolute and effective thinking."
author: john
categories: [ Jekyll, tutorial ]
image: assets/images/3.jpg
toc: true
beforetoc: "This is the paragraph before TOC where I can shortly describe what this post is about before actually displaying the TOC "
```

So the output would be:

**Education must also train one for quick, resolute and effective thinking.**

_This is the paragraph before TOC where I can shortly describe what this post is about before actually displaying the TOC._

Table of Content

Actual, usual {{content}}

**Comment by rahulkumarsingh73690** [comment]
Okay so it would be manually.

**Comment by wowthemesnet** [comment]
I'm thinking if I set a dynamic first paragraph, can conflict. In example, what if the first paragraph of the user is actually a list. Or another image? Does this make sense? This way you have total control of what you want to emphasize before TOC and also doesn't create potential conflicts as the ones described.

**Comment by rahulkumarsingh73690** [comment]
Okay I understand but beforetoc: is not worked for me

**Comment by wowthemesnet** [comment]
Well, I haven't implemented yet, I wanted to consult with you guys first :)

**Comment by rahulkumarsingh73690** [comment]
Ohh that's why it not worked for me.

**Comment by wowthemesnet** [comment]
Working on it right now! 

![2019-03-22_11h48_15](https://user-images.githubusercontent.com/5597992/54814512-96305280-4c98-11e9-86dd-be6d57008705.png)

**Comment by wowthemesnet** [comment]
Ok, you can check now!

**Comment by rahulkumarsingh73690** [comment]
Yoo, It worked for me. Thanks 😀
