### ISSUE TITLE
Jumbotron for tags

### ISSUE THREAD

**Issue by leninalbertolp** [wowthemesnet/mediumish-theme-jekyll#7]
Hello guys, sorry for my bad grammar, but English is not my language I support in a translator.
First of all thanks for this excellent theme, this cool.

The selector  ``.jumbotron.fortags .col-md-4`` has a padding top by 13% what causes the h2 not to center properly inside the container
![window1](https://user-images.githubusercontent.com/8427648/41989630-f7f4b3ac-7a0d-11e8-8338-0e1e3d1824b6.jpg)

is solved by adding flex properties or applied bootstrap classes ``d-flex align-items-center justify-content-center`` In the HTML
![window2](https://user-images.githubusercontent.com/8427648/41989832-9f1587ce-7a0e-11e8-9140-ae2061fe06d5.jpg)

The other is that in the screen.css document there is an empty rule
![regla-vacia](https://user-images.githubusercontent.com/8427648/41989956-1383dbf6-7a0f-11e8-8af8-1360afa9b3f3.jpg)

That's all for now, keep up with your excellent work and again thanks for theme

**Comment by wowthemesnet** [comment]
Thanks @leninalbertolp , updated!
