### ISSUE TITLE
Meta description not updating

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#74]
Issue on this site: https://takanodan.net/

```
<meta name="description" content="Reviews on anime and manga!" />
<meta property="og:description" content="Reviews on anime and manga!" />
```

In `_config.yml`: 

![image](https://user-images.githubusercontent.com/9038673/54719254-506a7180-4b54-11e9-8b7b-2ee09a38afb7.png)

How can I update the meta description?

Thanks!

**Comment by wowthemesnet** [comment]
All right, removed meta_description from yml , it is automatically generated by the seo plugin anyway (from the `description`). That thing made sense before jekyll_seo was implemented.

**Comment by GiacomoLaw** [comment]
Thanks!
