### ISSUE TITLE
Preventing ids from showing in sitemap?

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#75]
![image](https://user-images.githubusercontent.com/9038673/54719576-28c7d900-4b55-11e9-9c90-f9d2ed9caa8b.png)

My sitemap is generating category links with the id. How can I prevent this?

Thanks!

**Comment by wowthemesnet** [comment]
What if you add `sitemap: false` to Categories page?
Taken from _jekyll-sitemap_ [example](https://github.com/jekyll/jekyll-sitemap/blob/dbc18f15357444d58cab3b61d6f303b772914ae5/spec/fixtures/some-subfolder/exclude-this-page.html).

**Comment by GiacomoLaw** [comment]
Yep, the categories page has sitemap false in it, and that’s why it isn’t showing in the sitemap. 

Thanks!

**Comment by wowthemesnet** [comment]
I don't understand where they come from, I can't see them in [demo](https://wowthemesnet.github.io/mediumish-theme-jekyll/sitemap.xml).

**Comment by wowthemesnet** [comment]
What settings do you have for jekyll_sitemap?

**Comment by wowthemesnet** [comment]
Could they be from the menu? Are those the only one generated?

**Comment by GiacomoLaw** [comment]
I removed them manually from the sitemap

**Comment by wowthemesnet** [comment]
Oh, ok. So it's not a fix. I will still look into.

**Comment by GiacomoLaw** [comment]
Thanks.
