### ISSUE TITLE
Where should ads be placed?

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#76]
Hi there,

Got ads approved on my site https://takanodan.net but they don't look too good. I'm wondering where would be the best place to place them?

Thanks!

**Comment by wowthemesnet** [comment]
Yeah, it only looks good if you have full width featured images right under.

**Comment by wowthemesnet** [comment]
I don't know, I guess that's the thing with adsense, the placement and type of ad really depends on the user's layout.

**Comment by wowthemesnet** [comment]
In example, [here](https://takanodan.net/2019/03/death-note/) it looks good.

**Comment by GiacomoLaw** [comment]
I like it on desktop, but on mobile it looks like this: https://i.imgur.com/8rxDAlg.jpg

Guess it’s a limitation with Adsense. Is there a way to add in feed ads?

Thanks!
