### ISSUE TITLE
Issue in Lazyload

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [wowthemesnet/mediumish-theme-jekyll#79]
When I implemented the Lazy load on my website featured image cut (not the main problem). The main problem is to implement lazy load as scroll effect. I checked in chrome inspect tools all image load immediately after some second that does not matter. I prefer you to add lazyload as scroll effect.

**Comment by wowthemesnet** [comment]
Do you have a live link?

**Comment by wowthemesnet** [comment]
On my end they only load when I scroll to them, until then it's a fake src:

![2019-03-22_16h42_53](https://user-images.githubusercontent.com/5597992/54830733-b6283c00-4cc1-11e9-8c6e-4f929d946ddf.png)

**Comment by rahulkumarsingh73690** [comment]
Here is the live link - https://www.andrimo.com

**Comment by wowthemesnet** [comment]
Ok, I see the cut image issue. I'll push a fix. 

About the lazy load, I get the expected behaviour on your site as well.


![not-loaded](https://user-images.githubusercontent.com/5597992/54831838-c214fd80-4cc3-11e9-9270-f094daf45ba1.png)


![loaded](https://user-images.githubusercontent.com/5597992/54831853-c6d9b180-4cc3-11e9-8308-f5e21007001d.png)

Or am I missing something?

**Comment by rahulkumarsingh73690** [comment]
Yes it worked on homepage. Sorry I forget to mention. it's not working on post.

**Comment by wowthemesnet** [comment]
Oh, ok. Yes, I only implemented lazy load on card images and post featured image for now.

**Comment by rahulkumarsingh73690** [comment]
😀😀 I know just confirming from you. And what about featured image wrong size.

**Comment by wowthemesnet** [comment]
That's fixed, I forgot to say.

**Comment by GiacomoLaw** [comment]
All working well on my site.

**Comment by wowthemesnet** [comment]
Yes, I know, for the demo too. But this is a fix for longer titles, now the image has a dynamic height accordingly.

**Comment by rahulkumarsingh73690** [comment]
Fixed image issue in featured image. I created issue for remembering you about lazyload implementing for post.

**Comment by rahulkumarsingh73690** [comment]
![Home _ Andrimo - Google Chrome 23-03-2019 12_20_57](https://user-images.githubusercontent.com/37482171/54862825-4ddf6600-4d66-11e9-8b5d-d179fbc6acc1.png)
Not fixed. When you are in the first commit of lazyload featured image is good. But after 2nd the problem starting

**Comment by wowthemesnet** [comment]
It looks like your css is slightly different. In your screen.css file you currently have:

```
.featured-box-img-cover {
    object-fit: cover;
    max-height: 100%;
}
```

Instead of [this](https://github.com/wowthemesnet/mediumish-theme-jekyll/blob/master/assets/css/screen.css#L126).
