### ISSUE TITLE
Implement Lazyload in Post

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [wowthemesnet/mediumish-theme-jekyll#80]
Implement Lazyload features in post. This is only for remembering you when fixed then close this issue.

**Comment by GiacomoLaw** [comment]
Are you optimising your images before adding them to your site? That can save you a great deal of site speed time.

**Comment by rahulkumarsingh73690** [comment]
Yes. I am optimising my image.

**Comment by rahulkumarsingh73690** [comment]
Most of people doesn't care about page speed but I always. I am working in SEO over 3 years and I analysed the maximum not ranked pages have low speed.

**Comment by rahulkumarsingh73690** [comment]
So I tried to improve till the possibility end.

**Comment by GiacomoLaw** [comment]
> Most of people doesn't care about page speed

I wouldn't say this is true - it's very well known the large impact on the amount of users slow pages have.

I too also try to have the fastest page possible 😄

**Comment by rahulkumarsingh73690** [comment]
What is the status of Lazyload in Post @wowthemesnet
