### ISSUE TITLE
<1 star ratings don't work on Github pages

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#84]
Shows 0 stars. To test, simply change the value to 0.5.

Thanks!

**Comment by GiacomoLaw** [comment]
To update, anything under 1 does not work - 0.75, 0.25 etc do not work.

Thanks

**Comment by wowthemesnet** [comment]
On Github Pages they are not displayed at all? Is it a blank space? Nevermind, I will upload one now.

**Comment by GiacomoLaw** [comment]
They are displayed but as 0 stars.

**Comment by GiacomoLaw** [comment]
Doesn’t seem to be working on your build either.

**Comment by wowthemesnet** [comment]
Yes, I think I know why, it seems a Github minification issue on stars, I am trying now to fix it.

**Comment by GiacomoLaw** [comment]
Awesome, thanks.

**Comment by wowthemesnet** [comment]
Ah, yes, that was it. I imported the non scss version this time and it [works](https://wowthemesnet.github.io/mediumish-theme-jekyll/we-all-wait-for-summer/).

**Comment by GiacomoLaw** [comment]
Awesome, thanks. So I update `stars.scss` to `stars.css` and add the rendered file?

https://github.com/wowthemesnet/mediumish-theme-jekyll/commit/48d8c36e38787c3349e23155a4914e231f1bc1ac

Thanks

**Comment by wowthemesnet** [comment]
The manual update is this:
1. Add `_starsnonscss` in `sass` folder. [link](https://github.com/wowthemesnet/mediumish-theme-jekyll/tree/master/_sass)

2. Replace in `main.css`  `stars` with `starsnonscss`. [link](https://github.com/wowthemesnet/mediumish-theme-jekyll/blob/master/assets/css/main.scss)

**Comment by GiacomoLaw** [comment]
Awesome, thanks. Appreciate the support of the theme.

**Comment by wowthemesnet** [comment]
You can delete the old _stars.scss, I'm just leaving it in the repository for anyone who wants to have the preprocessor.
