### ISSUE TITLE
Comment count not showing up on latest posts?

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#85]
On my old posts, comment count is showing fine: https://takanodan.net/2019/02/slime-review/

However, on my latest, it does not show at all: https://takanodan.net/2019/03/slime-s1/

Is there a delay with Disqus, or is it an issue on my end?

Thanks!

**Comment by GiacomoLaw** [comment]
Seems like it's Disqus taking some time to recognize a new post. My bad, apologies for the impatience.

**Comment by rahulkumarsingh73690** [comment]
Yeah, It takes too much time but this issue is Disqus. Have you reported this issue?

**Comment by GiacomoLaw** [comment]
Only takes around 20 minutes, no biggie.
