### ISSUE TITLE
Advanced Idea to Improve theme

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [wowthemesnet/mediumish-theme-jekyll#86]
Hello, 
This time many themes support Night Mode. Is it possible in this theme? Like this - https://codepen.io/sashatran/pen/rPaLgG

**Comment by wowthemesnet** [comment]
It's a nice idea, but it takes some time to create a totally different stylesheet for the dark background.

**Comment by MihajloNesic** [comment]
This is really easy to implement with [dark-mode-switch](https://github.com/coliff/dark-mode-switch). I've used it on [my website](https://mihajlonesic.gitlab.io/). It can be tedious, because you must create a second stylesheet just for dark mode.

**Comment by dopewind** [comment]
+1
