### ISSUE TITLE
Create Discourse forum for jekyll

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [wowthemesnet/mediumish-theme-jekyll#87]
This question is not related to this project.

I want to know is any way to create discourse like form in Jekyll. I know GitHub provide static hosting.

**Comment by GiacomoLaw** [comment]
Discourse is open source, so you can set it up. However it’s a dynamic site and therefore you’ll need hosting other than GitHub. 

Also please don’t start issues unrelated to Mediumish in the Mediumish repo. There are plenty of articles on setting up discourse.
