### ISSUE TITLE
Serve profile pictures from a custom URL/local, not Gravatar

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#88]
This would be a great feature to have, as many do not want to use Gravatar. Whilst it's easy enough to do with custom code, a better method could be used.

Will also help with site speed, as Gravatar serves images in `200px`, why it is only `30px` on the site.

Thanks

**Comment by muygalan** [comment]
> This would be a great feature to have, as many do not want to use Gravatar. Whilst it's easy enough to do with custom code, a better method could be used.
> 
> Will also help with site speed, as Gravatar serves images in `200px`, why it is only `30px` on the site.
> 
> Thanks

I'm literally fiddling with this as well. Can you tell me how you were able to replace the theme's gravatar with a custom photo? I tried relative linking to an image in my assets folder and absolute linking to an image on the web, but neither method worked.

**Comment by GiacomoLaw** [comment]
Search your project for the class `author-thumb` and you’ll find the link for the gravater, replace it with your image link. 

https://github.com/wowthemesnet/mediumish-theme-jekyll/blob/be4679054c9b500bfa6cafe44685706254e24776/_includes/featuredbox.html#L38

**Comment by muygalan** [comment]
@GiacomoLaw Thanks for the quick reply!

Pardon me if this is a dumb question, but do I need to replace the gravatar link for just _this_ one instance or in every file that has an `author-thumb` class with a `src` linking to a gravatar url?

**Comment by GiacomoLaw** [comment]
Every file that has `author-thumb` with that link, yes.

**Comment by wowthemesnet** [comment]
Ok, done!
Make sure you set your local avatar  in [config](https://github.com/wowthemesnet/mediumish-theme-jekyll/blob/master/_config.yml#L27). If no local avatar is set, it grabs the gravatar.

**Comment by GiacomoLaw** [comment]
Thank you!
