### ISSUE TITLE
All stories posts not showing

### ISSUE THREAD

**Issue by alexsonnay** [wowthemesnet/mediumish-theme-jekyll#9]
I'm getting crazy : only posts with `featured: true` are showing. 

All the normal posts are invisible and the "All stories" section remains empty.

Any idea why ?

**Comment by stanfaire** [comment]
It's pagination not working properly.

Copy the relevant line of codes from there :

https://framagit.org/ParisEnSelle/planvelo/commit/7dd540437392b84400f411b2de24edfcdea5b6b6#de3150c01c3a946a6168173c4116741379fe3579
