### ISSUE TITLE
Add Ability to Subscribe in Same Page

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [wowthemesnet/mediumish-theme-jekyll#91]
I tried Subscribe Form But I found some issue when I fill email address and click sign up it redirects to MailChimp and then the filled email is gone. No one gonna fills two time their email. Implement Same as your Mundana Theme

**Comment by rahulkumarsingh73690** [comment]
@wowthemesnet Hey you could not update this theme :( 
Why?

**Comment by mariaathena** [comment]
I had the same concern so I just removed the input field from _layout/default in the alert-bar class. It makes the UX a bit better imo :)
