### ISSUE TITLE
What is popper.js used for?

### ISSUE THREAD

**Issue by GiacomoLaw** [wowthemesnet/mediumish-theme-jekyll#97]
`<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>`

Can't seem to find a use for it on the site. Seems to just be loaded in for no reason.

Thanks!

**Comment by farshadfahimi1371** [comment]
this is a library that use in bootstrap4
